on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          yarn ci

  test_action:
    runs-on: ubuntu-latest
    name: Test the summariser
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          yarn ci
      - name: Test json_spec_reporter_summariser
        uses: ./ # Uses an action in the root directory
        id: json_spec_reporter_summariser
        with:
          file_globs: |-
            ./tests/fixtures/**/*.json
            ./tests/fixtures/**/*.json
      - name: Get the summary from the output
        run: |
          echo "duration:                         ${{ steps.json_spec_reporter_summariser.outputs.duration }}"
          echo "example_count:                    ${{ steps.json_spec_reporter_summariser.outputs.example_count }}"
          echo "failure_count:                    ${{ steps.json_spec_reporter_summariser.outputs.failure_count }}"
          echo "pending_count:                    ${{ steps.json_spec_reporter_summariser.outputs.pending_count }}"
          echo "errors_outside_of_examples_count: ${{ steps.json_spec_reporter_summariser.outputs.errors_outside_of_examples_count }}"
          
          echo "${{ fromJson(steps.json_spec_reporter_summariser.outputs.summary_string).version }}" | jq
